config/routes.rb
Rails.application.routes.draw do
    root 'samples#index'

  resources :auditors

	resources :samples

	resources :pieces

	resources :equipment

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample < ApplicationRecord
	has_many	:pieces
  belongs_to :equipment
  belongs_to :auditor
  
  validates_presence_of :sampledate,  message: "Story title is required"
	validates :sampledate, format: { with: /([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))/,  message: "Inserta un formato de fecha valido"	}
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all.order(sampledate: :desc)
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to samples_url, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to samples_url, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params 
      params.require(:sample).permit(:sample_type, :aql, :sampledate, :lot, :equipment_id, :auditor_id)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> impide que la muestra sea guardada:</h2>

      <ul>
		<% sample.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
      </ul>
    </div>
  <% end %>
  <%= javascript_include_tag 'bootstrap-datepicker' %>						
  <script type="text/javascript">
		jQuery( window ).load( function() {
			// Element Attribute Helper
			function attrDefault($el, data_var, default_val) {
		    	if(typeof $el.data(data_var) != 'undefined') {
		      		return $el.data(data_var);
					} return default_val;
		  		}
			// Select2 Dropdown replacement
			if($.isFunction($.fn.select2)) {
				$(".select2").each(function(i, el) {
					var $this = $(el),
					opts = {
					allowClear: attrDefault($this, 'allowClear', false)
				};

				$this.select2(opts);
				$this.addClass('visible');

				//$this.select2("open");
		});


		if($.isFunction($.fn.niceScroll))
		{
			$(".select2-results").niceScroll({
				cursorcolor: '#d4d4d4',
				cursorborder: '1px solid #ccc',
				railpadding: {right: 3}
			});
		}
	}
		$("#muestreo").select2({
			minimumResultsForSearch: Infinity
		});

		$("#equipment-select").select2();
		
		$("#auditor-select").select2({
			minimumResultsForSearch: Infinity
		});
		
		$(".datepicker").datepicker("update", new Date());	
	
	
	
	// Added on v1.1.4
	$(".input-spinner").each(function(i, el)
	{
		var $this = $(el),
			$minus = $this.find('button:first'),
			$plus = $this.find('button:last'),
			$input = $this.find('input'),

			minus_step = attrDefault($minus, 'step', -0.5),
			plus_step = attrDefault($minus, 'step', 0.5),

			min = attrDefault($input, 'min', null),
			max = attrDefault($input, 'max', null);


		$this.find('button').on('click', function(ev)
		{
			ev.preventDefault();

			var $this = $(this),
				val = $input.val(),
				step = attrDefault($this, 'step', $this[0] == $minus[0] ? -0.5 : 0.5);

			if( ! step.toString().match(/^[0-9-\.]+$/))
			{
				step = $this[0] == $minus[0] ? -0.5 : 0.5;
			}

			if( ! val.toString().match(/^[0-9-\.]+$/))
			{
				val = 0;
			}

			$input.val( parseFloat(val) + step ).trigger('keyup');
		});

		$input.keyup(function()
		{
			if(min != null && parseFloat($input.val()) < min)
			{
				$input.val(min);
			}
			else

			if(max != null && parseFloat($input.val()) > max)
			{
				$input.val(max);
			}
		});

	});
	
});
  </script>

  				<form role="form" class="form-horizontal form-groups-bordered">
	
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">Tipo de Muestreo</label>
						
  						<div class="col-sm-4">
  							<%=form.select :sample_type, [ ['Muestreo Simple', 'Simple'], ['Doble Sampleo', 'Doble'] ], {}, {id: "muestreo"} %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">AQL</label>
						
  						<div class="col-sm-4">
							<div class="input-spinner">
								<button type="button" class="btn btn-success btn-sm">-</button>
								<%= form.text_field :aql, id: :sample_aql, class: 'form-control size-1 input-sm', value: "1.5", :data => {:min => '1', :max => '3' } %>
								<!--input type="text" class="" value="1.5" />-->
								<button type="button" class="btn btn-success btn-sm">+</button>
							</div>
							<!--<%= form.text_area :aql, id: :sample_aql %>-->
  							<%# form.text_field :employee, id: :auditor_employee, class: 'form-control', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">Fecha</label>
						
  						<div class="col-sm-4">
								<div class="input-group">
									<%= form.text_field :sampledate, id: :sample_sampledate, class: 'form-control datepicker', "data-date-format" => 'yyyy-mm-dd' %>
									<%# form.date_select :sampledate, id: :sample_sampledate %>
									<!--<input type="text" class="form-control datepicker" data-date-format="yyyy-mm-dd">-->
									
									<div class="input-group-addon">
										<a href="#"><i class="entypo-calendar"></i></a>
									</div>
								</div>
							<%# form.date_select :sampledate, id: :sample_sampledate %>
  							<%# form.text_field :employee, id: :auditor_employee, class: 'form-control', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">Lote</label>
						
  						<div class="col-sm-4">
							<%= form.text_field :lot, id: :sample_lot, class: 'form-control input-lg' %>
  							<%# form.text_field :employee, id: :auditor_employee, class: 'form-control', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">Modelo de Equipo</label>
						
  						<div class="col-sm-4">
							<%#form.select :sample_type, [ ['Muestreo Simple', 'Simple'], ['Doble Sampleo', 'Doble'] ], {}, {id: "muestreo"} %>
							<%= form.collection_select(:equipment_id, Equipment.all, :id, :equipment_type, {}, {id: "equipment-select"} ) %>
  							<%# form.text_field :employee, id: :auditor_employee, class: 'form-control', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label form-field">Auditor</label>
						
  						<div class="col-sm-4">
							<%= form.collection_select(:auditor_id, Auditor.all, :id, :name, {}, {id: "auditor-select"}) %>
  							<%# form.text_field :employee, id: :auditor_employee, class: 'form-control', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					
					

  					<div class="post-save-changes">
  						<div class="col-sm-offset-2 col-sm-2 actions update-button">
  							<%# form.submit "<i class='entypo-check'></i>Actualizar".html_safe, class: 'btn btn-green btn-lg btn-block btn-icon' %>
							<%= form.submit %>
  						</div>
  					</div>
  				</form>
				
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>
	<div class="row">
		<div class="col-sm-3">
			<h1 class="page-title">Muestreos</h1>
		</div>
		<div class="col-sm-4">
			<%= link_to '<i class="entypo-user-add"></i>Agregar'.html_safe, new_sample_path, class: 'btn btn-default btn-icon' %>
		</div>
	</div>
		
		
		<script type="text/javascript">
			 jQuery( window ).load( function() {
			var $table2 = jQuery( "#table-2" );

			$table2.DataTable( {
				dom: 'Bfrtip',
				buttons: [
					'copyHtml5',
					'excelHtml5',
					'csvHtml5',
					'pdfHtml5'
				]
			} );
			});
		</script>
			
		<table class="table table-bordered table-striped datatable" id="table-2">
			<thead>
				<tr>
					<th>
						<div class="checkbox checkbox-replace">
							<input type="checkbox" id="chk-1">
						</div>
					</th>
					<th>ID del Muestreo</th>
					<th>Tipo de Muestreo</th>
					<th>AQL</th>
					<th>Fecha</th>
					<th>Lote</th>
					<th>Tipo Equipo</th>
					<th>Auditor</th>
					<th>Acciones</th>
				</tr>
			</thead>
			
			<tbody>
			    <% @samples.each do |sample| %>
			         <tr>
	 					<td>
	 						<div class="checkbox checkbox-replace">
	 							<input type="checkbox" id="chk-1">
	 						</div>
	 					</td>
					   <td><%= sample.id %></td>
			           <td><%= sample.sample_type %></td>
			           <td><%= sample.aql %></td>
					   <td><%= sample.sampledate %></td>
					   <td><%= sample.lot %></td>
					   <td><%= sample.equipment.equipment_type %></td>
					   <td><%= sample.auditor.name %></td>
   						<td>
							
							<%= link_to '<i class="entypo-pencil"></i>Editar'.html_safe, edit_sample_path(sample), 
								class: "btn btn-default btn-sm btn-icon icon-left"  %>
							
							<%= link_to '<i class="entypo-cancel"></i>Borrar'.html_safe, sample, 
								class: "btn btn-danger btn-sm btn-icon icon-left", 
								method: :delete, 
								data: { confirm: 'Are you sure?' } %>
																
							<%= link_to '<i class="entypo-info"></i>Ver Muestreo'.html_safe, sample, 
								class: "btn btn-info btn-sm btn-icon icon-left" %>
						

   						</td>
			         </tr>
			  <% end %>
			  
				<% if @samples.size== 0%>
					<em> No existen Muestreos</em>
				<% end %>
			</tbody>
		</table>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>



	<form></form>  

  <h2>Basic Form Elements</h2>

  <br />

  <div class="row">
  	<div class="col-md-12">
		
  		<div class="panel panel-primary" data-collapsed="0">
		
  			<div class="panel-heading">
  				<div class="panel-title">
  					Default Form Inputs
  				</div>
				
  				<div class="panel-options">
  					<a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
  					<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
  					<a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
  					<a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
  				</div>
  			</div>
			
  			<div class="panel-body">
				
  				<form role="form" class="form-horizontal form-groups-bordered">
	
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label">ID</label>
  						<div class="col-sm-8">
							<%= @sample.id %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label">Tipo de Muestreo</label>
						
  						<div class="col-sm-8">
							<%= @sample.sample_type %>
  						</div>
  					</div>
					
					
  					
  				</form>
				
  			</div>
		
  		</div>
	
  	</div>
  </div>






<p>
  <strong>ID:</strong>
  <%= @sample.id %>
</p>

<p>
  <strong>Tipo de Muestreo:</strong>
  <%= @sample.sample_type %>
</p>

<p>
  <strong>AQL:</strong>
  <%= @sample.aql %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @sample.sampledate %>
</p>

<p>
  <strong>Lote:</strong>
  <%= @sample.lot %>
</p>

<p>
  <strong>Tipo Equipo:</strong>
  <%# link_to @sample.equipment.equipment_type, equipment_path(@sample.equipment.id) %>
  <%= @sample.equipment.equipment_type %>
</p>

  <strong>Auditor:</strong>
  <%= link_to @sample.auditor.name, auditor_path(@sample.auditor.id) %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>