config/routes.rb
Rails.application.routes.draw do
    root 'samples#index'

  resources :auditors

	resources :samples

	resources :pieces

	resources :equipment

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_header.html.erb
  <head>
    <title>Audits</title>
    <%= csrf_meta_tags %>
	<%# stylesheet_link_tag 'bootstrap' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato|Oswald|Playfair+Display|Raleway|Roboto',
		'neon-theme', 'white', 
		'select2-bootstrap', 'entypo', 
		media: 'all', 'data-turbolinks-track': 'reload' %>
	<%# stylesheet_link_tag 'entypo' %>
	<%= stylesheet_link_tag 'datatables' %>
	<%= stylesheet_link_tag 'select2' %>
	<%= javascript_include_tag 'jquery-1.11.3.min' %>
	<%= javascript_include_tag 'neon-custom' %>
	<%= javascript_include_tag	'bootstrap' %>
    <%= javascript_include_tag 'application', 'icheck' %>
	<%= javascript_include_tag 'datatables' %>
	<%= javascript_include_tag 'select2' %>
	<%= stylesheet_link_tag 'neon-forms' %>
	<%= stylesheet_link_tag 'neon-core' %>
  </head>

app/views/partials/_sidebar.html.erb
	<div class="sidebar-menu">

		<div class="sidebar-menu-inner">
			
			<header class="logo-env">
				<!-- logo -->
				<div class="logo">
					<%= image_tag ("/assets/logo\@2x.png") %>
				</div>
			</header>
			
									
			<ul id="main-menu" class="main-menu">
				<!-- add class "multiple-expanded" to allow multiple submenus to open -->
				<!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->
				<li>						
					<%= link_to '<i class="entypo-list"></i><span class="title">Muestreos</span>'.html_safe, samples_path %>
				</li>
		
				<li>
					<%= link_to '<i class="entypo-target"></i><span class="title">Piezas Muestreadas</span>'.html_safe, pieces_path %>
				</li>
				<li>
					<%= link_to '<i class="entypo-database"></i><span class="title">Equipos</span>'.html_safe, equipment_index_url %>
				</li>	
				<li>
					<%= link_to '<i class="entypo-user"></i><span class="title">Auditores</span>'.html_safe, auditors_path %>
				</li>		
		</div>

	</div>