config/routes.rb
Rails.application.routes.draw do
    root 'samples#index'

  resources :auditors

	resources :samples

	resources :pieces

	resources :equipment

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auditor.rb
class Auditor < ApplicationRecord
	has_many :samples
end

app/controllers/auditor_controller.rb
class AuditorController < ApplicationController
  def index
    @auditors = Auditor.all
  end

  def show
  end

  def new
    @auditor= Auditor.new
  end

  def edit
  end

  def destroy
    @auditor.destroy
  end
  
  private
      # Use callbacks to share common setup or constraints between actions.
      def set_auditor
        @auditor = Auditor.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def auditors_params
        params.require(:auditor).permit(:name, :employee, :birth, :status)
      end
  
end

app/controllers/auditors_controller.rb
class AuditorsController < ApplicationController
  before_action :set_auditor, only: [:show, :edit, :update, :destroy]

  # GET /auditors
  # GET /auditors.json
  def index
    @auditors = Auditor.all
    @last_auditor = Auditor.last
  end

  # GET /auditors/1
  # GET /auditors/1.json
  def show
    @auditor = Auditor.find(params[:id])
    @auditor_samples = @auditor.samples.limit(10)
  end

  # GET /auditors/new
  def new
    @auditor = Auditor.new
  end

  # GET /auditors/1/edit
  def edit
  end

  # POST /auditors
  # POST /auditors.json
  def create
    @auditor = Auditor.new(auditor_params)

    respond_to do |format|
      if @auditor.save
        format.html { redirect_to @auditor, notice: 'Auditor was successfully created.' }
        format.json { render :show, status: :created, location: @auditor }
      else
        format.html { render :new }
        format.json { render json: @auditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditors/1
  # PATCH/PUT /auditors/1.json
  def update
      respond_to do |format|
        if @auditor.update(auditor_params)
          format.html { redirect_to @auditor, notice: 'Auditor was successfully updated.' }
          format.json { render :show, status: :ok, location: @auditor }
        else
          format.html { render :edit }
          format.json { render json: @auditor.errors, status: :unprocessable_entity }
        end
      end
    end
  
  # DELETE /auditors/1
  # DELETE /auditors/1.json
  def destroy
    @auditor.destroy
    respond_to do |format|
      format.html { redirect_to auditors_url, notice: 'Auditor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auditor
      @auditor = Auditor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
    def auditor_params
          params.require(:auditor).permit(:name, :employee)
    end
    
end

app/helpers/auditor_helper.rb
module AuditorHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/views/auditor/_form.html.erb
<%= form_with(model: auditor, local: true) do |f| %>

 <% if auditor.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(auditor.errors.count, "error") %> prohibited this auditor from being saved:</h2>

     <ul>
     <% auditor.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 
 
 
 <h2>Basic Form Elements</h2>
 <br />


 <div class="row">
 	<div class="col-md-12">
		
 		<div class="panel panel-primary" data-collapsed="0">
		
 			<div class="panel-heading">
 				<div class="panel-title">
 					Default Form Inputs
 				</div>
				
 				<div class="panel-options">
 					<a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
 					<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
 					<a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
 					<a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
 				</div>
 			</div>
			
 			<div class="panel-body">
				
 				<form role="form" class="form-horizontal form-groups-bordered">
	
 					<div class="form-group">
 						<label for="field-1" class="col-sm-3 control-label">Field 1</label>
						
 						<div class="col-sm-5">
 							<input type="text" class="form-control" id="field-1" placeholder="Placeholder">
 						</div>
 					</div>
					
 	
				
				</form>
				
				
 			</div>
		
 		</div>
	
 	</div>
 </div>
 
 

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name, id: :auditor_name %>
  </div>

  <div class="field">
    <%= f.label :employee %>
    <%= f.text_area :employee, id: :auditor_employee %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  
  

  
  
  
<% end %>

app/views/auditor/destroy.html.erb
<h1>Auditor#destroy</h1>
<p>Find me in app/views/auditor/destroy.html.erb</p>

app/views/auditor/edit.html.erb
<h1>Auditor#edit</h1>
<p>Find me in app/views/auditor/edit.html.erb</p>
<%= render 'form', auditor: @auditor %>

app/views/auditor/index.html.erb
		<h3>Auditores</h3>
		<%= link_to 'New Auditor', new_auditor_path %>
		
		
		<table class="table table-bordered table-striped datatable" id="table-2">
			<thead>
				<tr>
					<th>
						<div class="checkbox checkbox-replace">
							<input type="checkbox" id="chk-1">
						</div>
					</th>
					<th>Nombre del Auditor</th>
					<th>No. de Empleado</th>
					<th>Acciones</th>
				</tr>
			</thead>
			
			<tbody>
			    <% @auditors.each do |auditor| %>
			         <tr>
	 					<td>
	 						<div class="checkbox checkbox-replace">
	 							<input type="checkbox" id="chk-1">
	 						</div>
	 					</td>
			           <td><%= auditor.name %></td>
			           <td><%= auditor.employee %></td>
   						<td>
							
							<%= link_to '<i class="entypo-pencil"></i>Editar'.html_safe, auditor_edit_path(:id => auditor.id), class: "btn btn-default btn-sm btn-icon icon-left"  %>
																
   							<a href="#" class="btn btn-default btn-sm btn-icon icon-left">
   								<i class=""></i>
   									Edit
   								</a>
						
   							<a href="#" class="btn btn-danger btn-sm btn-icon icon-left">
   								<i class="entypo-cancel"></i>
   									Delete
   								</a>
						
   							<a href="#" class="btn btn-info btn-sm btn-icon icon-left">
   								<i class="entypo-info"></i>
   									Profile
   							</a>
   						</td>
			         </tr>
			  <% end %>
				<% if @auditors.size== 0%>
					<em> No existen auditores</em>
				<% end %>
			</tbody>
		</table>

app/views/auditor/list.html.erb
		<h3>Auditores</h3>
		
		
		<table class="table table-bordered table-striped datatable" id="table-2">
			<thead>
				<tr>
					<th>
						<div class="checkbox checkbox-replace">
							<input type="checkbox" id="chk-1">
						</div>
					</th>
					<th>Nombre del Auditor</th>
					<th>No. de Empleado</th>
					<th>Acciones</th>
				</tr>
			</thead>
			
			<tbody>
				<% @auditors =  %>
			    <% @auditors.each do |auditor| %>
			         <tr>
	 					<td>
	 						<div class="checkbox checkbox-replace">
	 							<input type="checkbox" id="chk-1">
	 						</div>
	 					</td>
			           <td><%= auditor.name %></td>
			           <td><%= auditor.employee %></td>
   						<td>
							
							<%= link_to '<i class="entypo-pencil"></i>Editar'.html_safe, auditor_edit_path(:id => auditor.id), class: "btn btn-default btn-sm btn-icon icon-left"  %>
																
   							<a href="#" class="btn btn-default btn-sm btn-icon icon-left">
   								<i class=""></i>
   									Edit
   								</a>
						
   							<a href="#" class="btn btn-danger btn-sm btn-icon icon-left">
   								<i class="entypo-cancel"></i>
   									Delete
   								</a>
						
   							<a href="#" class="btn btn-info btn-sm btn-icon icon-left">
   								<i class="entypo-info"></i>
   									Profile
   							</a>
   						</td>
			         </tr>
			  <% end %>
				<% if @auditors.size== 0%>
					<em> No existen auditores</em>
				<% end %>
			</tbody>
		</table>

app/views/auditor/new.html.erb
<h1>New Auditor</h1>

<%= render 'form', auditor: @auditor %>

<%= link_to 'Back', auditors_path %>

app/views/auditor/show.html.erb
<h1>Auditor#show</h1>
<p>Find me in app/views/auditor/show.html.erb</p>