config/routes.rb
Rails.application.routes.draw do
    root 'samples#index'

  resources :auditors

	resources :samples

	resources :pieces

	resources :equipment

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auditor.rb
class Auditor < ApplicationRecord
	has_many :samples
end

app/controllers/auditor_controller.rb
class AuditorController < ApplicationController
  def index
    @auditors = Auditor.all
  end

  def show
  end

  def new
    @auditor= Auditor.new
  end

  def edit
  end

  def destroy
    @auditor.destroy
  end
  
  private
      # Use callbacks to share common setup or constraints between actions.
      def set_auditor
        @auditor = Auditor.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def auditors_params
        params.require(:auditor).permit(:name, :employee, :birth, :status)
      end
  
end

app/controllers/auditors_controller.rb
class AuditorsController < ApplicationController
  before_action :set_auditor, only: [:show, :edit, :update, :destroy]

  # GET /auditors
  # GET /auditors.json
  def index
    @auditors = Auditor.all
    @last_auditor = Auditor.last
  end

  # GET /auditors/1
  # GET /auditors/1.json
  def show
    @auditor = Auditor.find(params[:id])
    @auditor_samples = @auditor.samples.limit(10)
  end

  # GET /auditors/new
  def new
    @auditor = Auditor.new
  end

  # GET /auditors/1/edit
  def edit
  end

  # POST /auditors
  # POST /auditors.json
  def create
    @auditor = Auditor.new(auditor_params)

    respond_to do |format|
      if @auditor.save
        format.html { redirect_to @auditor, notice: 'Auditor was successfully created.' }
        format.json { render :show, status: :created, location: @auditor }
      else
        format.html { render :new }
        format.json { render json: @auditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditors/1
  # PATCH/PUT /auditors/1.json
  def update
      respond_to do |format|
        if @auditor.update(auditor_params)
          format.html { redirect_to @auditor, notice: 'Auditor was successfully updated.' }
          format.json { render :show, status: :ok, location: @auditor }
        else
          format.html { render :edit }
          format.json { render json: @auditor.errors, status: :unprocessable_entity }
        end
      end
    end
  
  # DELETE /auditors/1
  # DELETE /auditors/1.json
  def destroy
    @auditor.destroy
    respond_to do |format|
      format.html { redirect_to auditors_url, notice: 'Auditor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auditor
      @auditor = Auditor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
    def auditor_params
          params.require(:auditor).permit(:name, :employee)
    end
    
end

app/helpers/auditor_helper.rb
module AuditorHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/views/auditors/_form.html.erb
<%= form_with(model: auditor, local: true) do |form| %>

  <% if auditor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auditor.errors.count, "error") %> prohibited this auditor from being saved:</h2>

      <ul>
      <% auditor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	
	 
  <br />

  <div class="row">
  	<div class="col-md-12">
		
  		<div class="panel panel-primary" data-collapsed="0">
		
  			<div class="panel-heading">
  				<div class="panel-title">
  					Default Form Inputs
  				</div>
				
  				<div class="panel-options">
  					<a id="algo" href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
  					<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
  					<a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
  					<a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
  				</div>
  			</div>
			
  			<div class="panel-body">
				
  				<form role="form" class="form-horizontal form-groups-bordered">
	
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label">Nombre del Auditor</label>
						
  						<div class="col-sm-4">
  							<%= form.text_field :name, id: :auditor_name, class: 'form-control input-lg', id: 'field-1', placeholder: 'Nombre del Auditor' %>
  						</div>
  					</div>
					
  					<div class="form-group">
  						<label for="field-1" class="col-sm-2 control-label">Número de Empleado</label>
						
  						<div class="col-sm-4">
  							<%= form.text_field :employee, id: :auditor_employee, class: 'form-control input-lg', id: 'field-2', placeholder: '# Empleado' %>
  						</div>
  					</div>
					

  					<div class="post-save-changes">
  						<div class="col-sm-offset-2 col-sm-2 actions update-button">
  							<%# form.submit "<i class='entypo-check'></i>Actualizar".html_safe, class: 'btn btn-green btn-lg btn-block btn-icon' %>
							<%= button_tag(type: "submit", class: "btn btn-green btn-lg btn-block btn-icon") do %>
							    <i class='entypo-check'></i>Enviar
							<% end %>
							
  						</div>
  					</div>
  				</form>
				
  			</div>
		
  		</div>
	
  	</div>
  </div>
  
	<!-- Sample Modal (Default skin) -->
	<div class="modal fade" id="sample-modal-dialog-1">
		<div class="modal-dialog">
			<div class="modal-content">
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Widget Options - Default Modal</h4>
				</div>
				
				<div class="modal-body">
					<p>Now residence dashwoods she excellent you. Shade being under his bed her. Much read on as draw. Blessing for ignorant exercise any yourself unpacked. Pleasant horrible but confined day end marriage. Eagerness furniture set preserved far recommend. Did even but nor are most gave hope. Secure active living depend son repair day ladies now.</p>
				</div>
				
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Save changes</button>
				</div>
			</div>
		</div>
	</div>

  
  
<% end %>

app/views/auditors/destroy.html.erb
<h1>Auditors#destroy</h1>
<p>Find me in app/views/auditors/destroy.html.erb</p>

app/views/auditors/edit.html.erb
	<div class="row">
		<div class="col-sm-11">
			<h1 class="page-title">Edición de Auditor</h1>
		</div>
		<div class="col-sm-1">
			<%= link_to '<i class="entypo-back"></i>Atras'.html_safe, auditors_path, class: 'btn btn-blue btn-icon' %>
		</div>
	</div>





<%= render 'form', auditor: @auditor %>

<%= link_to 'Show', @auditor %> |
<%= link_to 'Back', auditors_path %>

app/views/auditors/index.html.erb
<p id="notice"><%= notice %></p>
	<div class="row">
		<div class="col-sm-3">
			<h1 class="page-title">Auditores</h1>
		</div>
		<div class="col-sm-4">
			<%= link_to '<i class="entypo-user-add"></i>Agregar'.html_safe, new_auditor_path, class: 'btn btn-default btn-icon' %>
		</div>
	</div>

		
		<table class="table table-bordered table-striped datatable" id="table-2">
			<thead>
				<tr>
					<th>
						<div class="checkbox checkbox-replace">
							<input type="checkbox" id="chk-1">
						</div>
					</th>
					<th>Nombre del Auditor</th>
					<th>No. de Empleado</th>
					<th>Acciones</th>
				</tr>
			</thead>
			
			<tbody>
			    <% @auditors.each do |auditor| %>
			         <tr>
	 					<td>
	 						<div class="checkbox checkbox-replace">
	 							<input type="checkbox" id="chk-1">
	 						</div>
	 					</td>
			           <td><%= auditor.name %></td>
			           <td><%= auditor.employee %></td>
   						<td>
							
							<%= link_to '<i class="entypo-pencil"></i>Editar'.html_safe, edit_auditor_path(auditor), 
								class: "btn btn-default btn-sm btn-icon icon-left"  %>
							
							<%= link_to '<i class="entypo-cancel"></i>Borrar'.html_safe, auditor, 
								class: "btn btn-danger btn-sm btn-icon icon-left", 
								method: :delete, 
								data: { confirm: 'Are you sure?' } %>
										
							<%= link_to '<i class="entypo-info"></i>Ver'.html_safe, auditor, 
								class: "btn btn-info btn-sm btn-icon icon-left"  %>
																		
   						</td>
			         </tr>
			  <% end %>
				<% if @auditors.size== 0%>
					<em> No existen auditores</em>
				<% end %>
			</tbody>
		</table>

app/views/auditors/new.html.erb
<div class="row">
	<div class="col-sm-3">
		<h1 class="page-title">Nuevo Auditor</h1>
	</div>
	<div class="col-sm-4">
		<%= link_to '<i class="entypo-back"></i>Atras'.html_safe, auditors_path, class: 'btn btn-blue btn-icon' %>
	</div>
</div>



<%= render 'form', auditor: @auditor %>

app/views/auditors/show.html.erb
<p id="notice"><%= notice %></p>

	<h1 class="page-title">Perfil del Auditor</h1>	
	<div class="profile-env">
		
		<header class="row">
			
			<div class="col-sm-7">
				
				<ul class="profile-info-sections">
					<li>
						<div class="profile-name">
							<h2>
								<%= link_to @auditor.name %>
						
							</h2>
							<span><a href="#">Auditor</a></span>
						</div>
					</li>
					
					<li>
						<div class="profile-stat">
							<h2><%=@auditor_samples.count %></h2>
							<span><a href="#">Muestreos</a></span>
						</div>
					</li>
					
					<li>
						<div class="profile-stat">
							<h2>108</h2>
							<span><a href="#">ejemplo</a></span>
						</div>
					</li>
				</ul>
				
			</div>
			
			<div class="col-sm-3">
				<div class="profile-buttons">
					<%= link_to '<i class="e-icon-pencil"></i>Editar'.html_safe, edit_auditor_path(@auditor), class: 'btn btn-default' %>
					<%= link_to '<i class="entypo-home"></i>Lista Auditores'.html_safe, auditors_path, class: 'btn btn-blue'  %>
					
				</div>
			</div>

		</header>
		
		<section class="profile-info-tabs">
			
			<div class="row">
									
					<table class="table table-bordered">
									<thead>
										<tr>
											<th class="text-center">ID</th>
											<th width="20%">Tipo de Muestreo</th>
											<th>AQL</th>
											<th>Fecha</th>
											<th>Lote</th>
											<th>Tipo Equipo</th>
											<th>Piezas Muestreadas</th>
											<th>Piezas Rechazadas</th>
										</tr>
									</thead>
				
									<tbody>
						  			    <% @auditor_samples.each do |sample| %>
						  			         <tr>
						  					   <td class="text-center"><%= sample.id %></td>
						  			           <td><%= sample.sample_type %></td>
						  			           <td class="text-center"><%= sample.aql %></td>
						  					   <td><%= sample.sampledate %></td>
						  					   <td class="text-center"><%= sample.lot %></td>
						  					   <td><%= sample.equipment.equipment_type %></td>
											   <td>Total: <%= sample.pieces.count %></td>
											   <td>Rechazadas: <%= sample.pieces.rejected.count %></td>
						  			         </tr>
						  			  <% end %>
									</tbody>
								</table>
					
			</div>
			
		</section>
		
	</div>